### ISSUE TITLE
can it support the mcwifipnp mod？ 

### ISSUE THREAD

**Issue by feipangjun** [bl4ckscor3/NoLANCheating#1]
link to the mod
https://modrinth.com/mod/mcwifipnp

**Comment by bl4ckscor3** [comment]
Do you have a link to the mod?

**Comment by feipangjun** [comment]
yes,here you are
https://modrinth.com/mod/mcwifipnp

**Comment by feipangjun** [comment]
![image](https://github.com/bl4ckscor3/NoLANCheating/assets/93204475/35350f93-3a8e-4019-b9ca-1b4853b3eaaa)
it looks like that

**Comment by feipangjun** [comment]
> Do you have a link to the mod?

yes,here you are
https://modrinth.com/mod/mcwifipnp
thanks a lot
and it looks like this
![image](https://github.com/bl4ckscor3/NoLANCheating/assets/93204475/afb31a67-6709-4a05-b071-931d71806f26)

**Comment by bl4ckscor3** [comment]
Thank you! I will take a look at it.

**Comment by bl4ckscor3** [comment]
This has now been released as part of v1.2!
