### ISSUE TITLE
Crashes with "Ennui's Bigger Inventories" in world creation screen

### ISSUE THREAD

**Issue by anoomolu** [bl4ckscor3/NoLANCheating#2]
Hiya.

Been using this mod for a while and it's been working great, so thank you! I noticed that when creating new worlds with both this and EBI installed, the game crashes, and the crashlog points to one of your mixins.

Using 1.21-fabric-v1.2.

https://mclo.gs/MXg0PeZ

**Comment by bl4ckscor3** [comment]
Thanks for reporting! An update with the fix for this has been released.
