### ISSUE TITLE
Lock lan

### ISSUE THREAD

**Issue by Yo-Snowpro** [bl4ckscor3/NoLANCheating#3]
have the ability to lock the lan allow cheats button on a world permenantly. like the difficulty lock for example.

**Comment by bl4ckscor3** [comment]
It is possible to lock it to always off. The purpose of this mod is to prevent players from enabling cheats when opening to LAN. As such, I don't think being able to lock it to always on is in scope of the mod. If you accidentally open to LAN with cheats disabled, you can always re-enter the world and open to LAN again.
